### ISSUE TITLE
xyPlot autocomplete stopped working

### ISSUE THREAD

**Issue by rjgoif** [TinyTerra/ComfyUI_tinyterraNodes#103]
At some point today in my xyPlot testing, I noticed that my loader nodes were out of date so I updated the ttn package. Since then, autocomplete hasn't worked in the xyPlot boxes. I tried restarting Comfy and refreshing the page, but that didn't work. 

I see in the readme that there is a setting to toggle somewhere, but I cannot find that with searching various menus. Did autocomplete just break or am I the broken one?

**Comment by TinyTerra** [comment]
the xyplot autocomplete is seperate to the general autocomplete, so the setting (in the config.ini file) wouldnt change it anyway..

The xyPlot node needs to be connected to a KSampler for the popup to show as well, otherwise it doesn't know which nodes to show info for. Which could be the case, or there might be something else going on..

**Comment by rjgoif** [comment]
I re-installed and updated my template saves and it started working.

Whatever it was, it probably had to do with the recent updates not jiving with my saved template versions. 

Closing as resolved. Thank you!

**Comment by rjgoif** [comment]
Ah. re-opening! I found the problem. It has to do with logic nodes, and seems to be independent of source. I'll post some minimum (non) working examples once I get closer to the bottom of things.

**Comment by TinyTerra** [comment]
It was being caused by nodes without widgets, should be fixed now :)

**Comment by rjgoif** [comment]
Nice work!
