### ISSUE TITLE
pipeedit problem

### ISSUE THREAD

**Issue by cardenluo** [TinyTerra/ComfyUI_tinyterraNodes#105]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/133877069/3cb7e046-0f0e-42ba-ae1e-a32800101bdf)
there is some wrong with piptedit ,how does it work

**Comment by TinyTerra** [comment]
All of the inputs are optional. 
You can either put in all of the inputs to compile them into a pipe line:
<img src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/9db0ee48-b2fa-4aa8-84ea-06f0d1c5daa4" width="300" />

Or you can 'edit' an existing pipe_line - any of the other inputs will override the same value currently in the pipe:
<img src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/6271d5d8-b02f-4c3c-af0e-f82217a17f00" width="300" />

The outputs on the right are the same values that are packed into the output pipe

**Comment by cardenluo** [comment]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/133877069/df85cbaf-74e0-46f2-8c16-9ac6bb6ed357)
Thank you for your reply，I really like your node. I’ve used it to build many workflows, and my thinking has become clearer.
1）Based on the test results, it is not possible to edit at both ends simultaneously in the pip edit mode. You can either only input or only output. So, will this node replace the “Pipe in and pipe out”?
2）However, in this case, re-editing is not supported?

**Comment by cardenluo** [comment]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/133877069/ac2fe966-2338-4d06-8762-09c78290d6a2)
Additionally, I’d like to express my personal experience with the loader, which feels a bit like a ‘behemoth.’ These ports are typically used in branch routes, and if they could be organized with a pipeout, it would make the workflow cleaner. This is just my personal impression .

**Comment by TinyTerra** [comment]
> 1）Based on the test results, it is not possible to edit at both ends simultaneously in the pip edit mode. You can either only input or only output. So, will this node replace the “Pipe in and pipe out”? 

That was a bug, apologies. it wasn't ouputting the data correctly, and i've now pushed a fix for it.

In that specific example though you could also take the clip from the loader/wherever the pipe is coming from and put it straight into the KSamp override.
(i feel like the pipeEdit is somewhat made redundant with the KSamp overrides since it achieves the same thing)

For example: the negative achieves the same result without the pipeEdit
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/b001adbe-a695-4a1b-be4e-c122222cbc9c)


however if you want to explicitly change the clip the pipe is using before the pos embed (to use in ksamp for lora loading)
you could do it like this
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/4c9f2b70-0ca3-4d3f-a6c9-5ddd72adfcd9)

That is if you want it explicitly for that specific conditioning as well, otherwise using the ksamp override would suffice.
In fact, if you were to put a clip into the pipeEdit, and then also use the KSamp override with a different clip, the override clip would take priority and modify the pipeline after the KSamp anyway.

> Additionally, I’d like to express my personal experience with the loader, which feels a bit like a ‘behemoth.’

That is somewhat by design, it's entire purpose is to group a large number of setup nodes into one, which makes it becoming a bit of a beast somewhat unavoidable

> These ports are typically used in branch routes, and if they could be organized with a pipeout, it would make the workflow cleaner.

That is a fair point, the main issue i have with adding that kind of 'metadata' info to the pipeline, is also already a bit of an issue with the entire pipeline currently. That is - it becomes incredibly murky and unclear what the data is / where its coming from.
Pipe is great at minimizing noodles but then it hides a lot of the actual flow.
Adding metadata into the mix would cause more confusion imo.

if you were to take the ksampler pipe should the metadata reference the original latent width/height, or the KSamp images? And you would perhaps expect the pos/neg string to also include external/added conditioning text - which wouldn't really be feasible.
on top of the added confusion/complexity it would then 'require' an additional node for a simple output
which in my mind, goes against the original idea of ttNs ideology of minimizing node soup

Thats my thought currently, but open to discuss it more

**Comment by cardenluo** [comment]
The new version, this pipeEDIT outputs and inputs are very smooth, which is great.
