### ISSUE TITLE
The Fullscreen keybinding should be changed

### ISSUE THREAD

**Issue by Immac** [TinyTerra/ComfyUI_tinyterraNodes#80]
<kbd>shift</kbd> + <kbd>up</kbd> is a very common binding when editing text (select text upwards), I find myself going fullscreen a lot of the time due to this, check usual keyboard shortcuts and appropriately change it, if possible something like <kbd>modifier</kbd> + <kbd>f11</kbd> could be a better key bind.

**Comment by hitrpr** [comment]
Agree, i hate it, because it switches on when I edit prompt and want to select.
It should not conflict to any editing key.

Also the hotkey can be still one-handeld, like shift+f3 or shift+F11

ATM the only way to fix it — change  tttnfullscreen.js at str 211 and set «read only» attr to file to be sure, it will not be rewritten.
was:
`        if ((e.code === 'ArrowUp' && e.shiftKey) && !e.ctrlKey) {`
fixed:
`        if ((e.code === 'F11' && e.shiftKey) && !e.ctrlKey) {`

**Comment by hitrpr** [comment]
okay, i made pull request for this change, let`s wait

**Comment by TinyTerra** [comment]
Merged the pull request
