### ISSUE TITLE
Conflict with another custom node?

### ISSUE THREAD

**Issue by KannManMachen** [TinyTerra/ComfyUI_tinyterraNodes#98]
Hey there,

I'm pretty new to the ComfyUI game. I have already loaded some community workflows and successfully installed the missing nodes with the help of the ComfyUI manager when needed.

But after installing the tinyterraNodes I could not load ComfyUI anymore. That is the error in the Terminal:

```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
zsh: abort      python3.11 main.py
```

Does anyone know if the tinyterraNode conflicts with one of the following nodes?

1. ComfyUl_Comfyroll_CustomNodes
2. ComfyUl_essentials
3. ComfyUI_IPAdapter_plus
4. ComfyUI_UltimateSDUpscale
5. ComfyUl-Crystools
6. ComfyUl-Flowty-TripoSR
7. ComfyUl-GlifNodes
8. ComfyUl-Impact-Pack
9. ComfyUl-KJNodes
10. ComfyUl-Manager
11. ComfyUl-QualityOfLifeSuit_Omar92
12. ComfyUl-SUPIR
13. ComfyUl-VideoHelperSuite
14. Derfuu_ComfyUl_ModdedNodes
15. rgthree-comfy
16. was-node-suite-comfyui

I'm working on a Mac. 

Cheers <3

**Comment by TinyTerra** [comment]
As far as i can tell it's an issue with your pytorch and/or numpy installation..
Or those within the conda environment..

If I'm honest im not too familiar with mac

**Comment by KannManMachen** [comment]
Okay, thx for the reply @TinyTerra :)

Maybe I should have installed a custom `venv` before installing ComfyUI. But apart from that – the `libomp.dylib` seems to be connected with your node-package. Can you tell me more about it?

**Comment by TinyTerra** [comment]
OpenMP is a multiprocessing / optimization API, however it (libomp.dylib) is not being used directly in the nodepack, it's embedded deeper in the torch or numpy imports..

As far as i can tell googling the issue, it is likely caused by incorrect/multiple versions of openmp being installed, see [here](https://stackoverflow.com/questions/55714135/how-can-i-fix-an-omp-error-15-initializing-libiomp5-dylib-but-found-libomp) (the top answer might help).
Which could be because the packaged version that comes bundled with numpy is causing an issue, see [here](https://community.anaconda.cloud/t/omp-error-15-initializing-libiomp5md-dll-but-found-libiomp5-already-initialized/48993/4) (The second comment might help).

**Comment by KannManMachen** [comment]
Thx again @TinyTerra,

for now I just moved the files `libiomp5.dylib` and `libomp.dylib` out of my conda library folder `/Users/XXX/miniconda3/lib`. The former error message disappeared (while having your tinyterraNodes installed) and ComfyUI is running :)

Lets hope there wont be any other issues by moving those files away from its origin  ¯\ _ (ツ) _ /¯

**Comment by TinyTerra** [comment]
If anything only slight optimisation will be missing, but it's possible it's installed elsewhere too and it's still being used..
But, glad it's working for you now
